name: 'GitHub Actions Mirror'

on: [push]

jobs:
  to_bot:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: commit
      run: |
        curl -X POST -k '${{ secrets.URL_SECRET }}' -d '{"ToUserUid": ${{ secrets.JSON_SECRET }},"SendToType": 2,"SendMsgType": "TextMsg","Content": "测试"}' 
        
